### ISSUE TITLE
Get a list of incoming headers

### ISSUE THREAD

**Issue by oscarcp** [toitlang/pkg-http#120]
I would like to have a method or variable that returns a list with all the incoming headers (just the keys) in the Request object (same as `Request.headers.headers_.keys`)

Current output of `Request.headers.headers_.keys`

```
>> print Request.headers.headers_.keys
["User-Agent", "Host", "Connection"...]
```

Example:

```
import http
server := http.Server
server.listen tcp_socket:: | req/http.Request resp/http.ResponseWriter |
  // Output a list of keys ["User-Agent", "Host", "Connection"...]
  print req.headers.all 
  // Iterate over keys
  req.headers.all.do: print "$it"
```

**Comment by floitsch** [comment]
Will be available in the next release of the package.
